#pragma once

#define SYSCALL_GET_ARGC 100
#define SYSCALL_GET_ARGV 101
#define SYSCALL_GET_ENV 102

#define SYSCALL_EXIT 190

#define SYSCALL_SERIAL_PRINT 200
#define SYSCALL_SERIAL_PRINTLN 201

#define SYSCALL_GLOBAL_PRINT 301
#define SYSCALL_GLOBAL_PRINTLN 302

#define SYSCALL_GLOBAL_CLS 310