#pragma once

#define SYSCALL_GET_ARGC 100
#define SYSCALL_GET_ARGV 101
#define SYSCALL_GET_ENV 102
#define SYSCALL_GET_PID 103
#define SYSCALL_PID_EXISTS 104
#define SYSCALL_GET_PARENT_PID 105
#define SYSCALL_GET_ELF_PATH 106
#define SYSCALL_GET_WORKING_PATH 107
#define SYSCALL_GET_ELF_PATH_PID 108
#define SYSCALL_REQUEST_NEXT_PAGES 110

#define SYSCALL_EXIT  130
#define SYSCALL_CRASH  131
#define SYSCALL_YIELD  132
#define SYSCALL_WAIT  133
#define SYSCALL_SET_PRIORITY 134
#define SYSCALL_WAIT_MSG  140

#define SYSCALL_LAUNCH_TEST_ELF_USER 170
#define SYSCALL_LAUNCH_TEST_ELF_KERNEL 171

#define SYSCALL_SERIAL_PRINT  200
#define SYSCALL_SERIAL_PRINTLN 201

#define SYSCALL_SERIAL_PRINT_CHAR 202
#define SYSCALL_SERIAL_READ_CHAR 203
#define SYSCALL_SERIAL_CAN_READ_CHAR 204


#define SYSCALL_GLOBAL_PRINT  301
#define SYSCALL_GLOBAL_PRINTLN 302
#define SYSCALL_GLOBAL_PRINT_CHAR  303
#define SYSCALL_GLOBAL_CLS  310

#define SYSCALL_ENV_GET_TIME_MS 400
#define SYSCALL_ENV_GET_TIME_MICRO_S 404
#define SYSCALL_ENV_GET_TIME_RTC 401
#define SYSCALL_ENV_GET_DESKTOP_PID 402
#define SYSCALL_ENV_GET_START_MENU_PID 403


// #define SYSCALL_ENV_GET_MOUSE_STATE 410
#define SYSCALL_ENV_GET_KEY_STATE 411
#define SYSCALL_ENV_GET_MOUSE_SENS 412


#define SYSCALL_ENV_SET_MOUSE_SENS 450

#define SYSCALL_MSG_GET_COUNT 510
#define SYSCALL_MSG_GET_MSG 511
#define SYSCALL_MSG_SEND_MSG 512
#define SYSCALL_MSG_GET_MSG_CONVO 513

#define SYSCALL_RNG_UINT64 600

// FS STUFF -> 700
#define SYSCALL_FS_CREATE_FILE 700
#define SYSCALL_FS_CREATE_FILE_WITH_SIZE 702
#define SYSCALL_FS_CREATE_FOLDER 701

#define SYSCALL_FS_DELETE_FILE 710
#define SYSCALL_FS_DELETE_FOLDER 711

// rename = move
#define SYSCALL_FS_RENAME_FILE 720
#define SYSCALL_FS_RENAME_FOLDER 721

#define SYSCALL_FS_COPY_FILE 730
#define SYSCALL_FS_COPY_FOLDER 731

#define SYSCALL_FS_FILE_EXISTS 740
#define SYSCALL_FS_FOLDER_EXISTS 741

#define SYSCALL_FS_GET_FILES_IN_PATH 750
#define SYSCALL_FS_GET_FOLDERS_IN_PATH 751
#define SYSCALL_FS_GET_DRIVES_IN_ROOT 752

#define SYSCALL_FS_GET_FILE_INFO 760
#define SYSCALL_FS_GET_FOLDER_INFO 761

#define SYSCALL_FS_READ_FILE_INTO_BUFFER 770
#define SYSCALL_FS_WRITE_FILE_FROM_BUFFER 771


// PARTITION STUFF -> 800


// WINDOW STUFF -> 900


#define SYSCALL_CLOSE_PROCESS 1000
#define SYSCALL_START_PROCESS 1010
#define SYSCALL_START_FILE 1011


#define SYSCALL_START_THREAD 1100
